CREATE TABLE IF NOT EXISTS vehiculos (
    id IDENTITY NOT NULL PRIMARY KEY,
    matricula VARCHAR NOT NULL,
    marca VARCHAR NOT NULL,
    modelo VARCHAR NOT NULL,
    motor VARCHAR NOT NULL,
    fechaMatriculacion DATE NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);